version = 3.10.1
runner.dialect = scala3

maxColumn = 120
preset = default
binPack.parentConstructors = true
includeCurlyBraceInSelectChains = false
trailingCommas = preserve

align.preset = most
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses.preset = true
optIn.breaksInsideChains = true

continuationIndent {
  callSite = 2
  defnSite = 2
  extendSite = 2
}

rewrite.rules = [RedundantBraces, RedundantParens, SortImports, SortModifiers, PreferCurlyFors]
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true
rewrite.redundantBraces.includeUnitMethods = true
rewrite.redundantBraces.stringInterpolation = true
newlines.penalizeSingleSelectMultiArgList = false
newlines.alwaysBeforeMultilineDef = false